name: Run workflow

inputs:
  workflow:
    description: workflow name
    type: string
    required: true
  ref:
    description: branch or tag name
    type: string
    default: ${{github.ref_name}}
  inputs:
    description: workflow inputs
    type: string
runs:
  using: node16
  main: dist/main/index.js
  post: dist/post/index.js
