declare const _default: import('@applitools/types').SpecDriver<Driver, Context, Element, Selector>;
export default _default;
export function isDriver(page: any): page is Driver;
export function isContext(frame: any): frame is Context;
export function isElement(element: any): element is Element;
export function isSelector(selector: any): selector is Selector;
export function transformSelector(selector: Selector | (string | { selector: string | Selector; type?: string; })): Selector;
export function extractContext(page: Driver | Context): Context;
export function isStaleElementError(err: any): boolean;
export function executeScript(frame: Context, script: string | ((arg: any) => any), arg: any): Promise<any>;
export function mainContext(frame: Context): Promise<Context>;
export function parentContext(frame: Context): Promise<Context>;
export function childContext(_frame: Context, element: Element): Promise<Context>;
export function findElement(frame: Context, selector: Selector, parent: Element): Promise<Element>;
export function findElements(frame: Context, selector: Selector, parent: Element): Promise<Array<Element>>;
export function getViewportSize(page: Driver): Promise<import('@applitools/types').Size>;
export function setViewportSize(page: Driver, size: import('@applitools/types').Size): Promise<void>;
export function getCookies(page: Driver): Promise<Array<import('@applitools/types').Cookie>>;
export function getTitle(page: Driver): Promise<string>;
export function getUrl(page: Driver): Promise<string>;
export function visit(page: Driver, url: string): Promise<void>;
export function takeScreenshot(page: Driver): Promise<string>;
export function click(frame: Context, element: Element | Selector): Promise<void>;
export function type(frame: Context, element: Element | Selector, keys: string): Promise<void>;
export function hover(frame: Context, element: Element | Selector): Promise<void>;
export function scrollIntoView(frame: Context, element: Element | Selector, align: boolean): Promise<void>;
export function waitUntilDisplayed(frame: Context, selector: Selector): Promise<void>;
export function build(env: any): Promise<[Driver, () => Promise<void>]>;
export type Driver = import('puppeteer').Page & { __applitoolsBrand?: never; };
export type Context = import('puppeteer').Frame & { __applitoolsBrand?: never; };
export type Element = import('puppeteer').ElementHandle<globalThis.Element> & { __applitoolsBrand?: never; };
export type Selector = string & { __applitoolsBrand?: never; };
